# Generated by Django 4.0.4 on 2022-05-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_patients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
